"""
Chart styling and market heuristics data for T2D Pulse dashboard
"""

# Define custom template for consistent chart styling
custom_template = {
    "layout": {
        "font": {"family": "Arial, sans-serif", "size": 12, "color": "#505050"},
        "paper_bgcolor": "rgba(0,0,0,0)",
        "plot_bgcolor": "rgba(248,249,250,1)",
        "margin": {"l": 40, "r": 40, "t": 40, "b": 40},
        "xaxis": {
            "showgrid": True,
            "gridwidth": 1,
            "gridcolor": "rgba(230,230,230,0.8)",
        },
        "yaxis": {
            "showgrid": True,
            "gridwidth": 1,
            "gridcolor": "rgba(230,230,230,0.8)",
            "zeroline": True,
            "zerolinecolor": "rgba(0,0,0,0.2)",
        },
        "legend": {
            "orientation": "h",
            "yanchor": "bottom",
            "y": 1.02,
            "xanchor": "right",
            "x": 1,
            "bgcolor": "rgba(255,255,255,0.9)",
        },
        "hovermode": "x unified",
    }
}

# Standardized color scheme for consistent indicator coloring
color_scheme = {
    "growth": "#3366CC",      # Blue for growth indicators (GDP, PCE, etc.)
    "inflation": "#FF9900",   # Orange for inflation metrics (CPI, PCEPI)
    "employment": "#DC3912",  # Red for employment metrics
    "market": "#7030A0",      # Purple for market indicators (NASDAQ, etc.)
    "rates": "#109618",       # Green for interest rates
    "target": "#109618",      # Green for target lines (dashed)
    "risk": "#FF0000",        # Red for risk indicators
    "positive": "#109618",    # Green for positive trends
    "negative": "#DC3912",    # Red for negative trends
    "neutral": "#999999",     # Gray for neutral reference lines
    "consumption": "#E67300", # Orange/amber for consumption metrics
    "secondary": "#5491F7"    # Light blue for secondary metrics/change indicators
}

# Market heuristics data
# This mapping connects indicators to their relevant market heuristics
market_heuristics = {
    "gdp": [
        {
            "trigger": "Real GDP YoY > 3.5%",
            "market_response": "Optimism on growth, rotation into cyclicals",
            "effect": "neutral",
            "effect_text": "Neutral to Slight underperformance",
            "rationale": "Strong GDP growth often rotates flows into industrials, financials, and value",
            "confidence": "Medium",
            "condition": lambda data: data['yoy_growth'].iloc[-1] > 3.5,
        },
        {
            "trigger": "Real GDP YoY 1.5% – 3.5%",
            "market_response": "Stable macro backdrop",
            "effect": "positive",
            "effect_text": "Supportive for broad tech sentiment",
            "rationale": "\"Goldilocks\" zone supports top-line growth without major policy risk",
            "confidence": "High",
            "condition": lambda data: 1.5 <= data['yoy_growth'].iloc[-1] <= 3.5,
        },
        {
            "trigger": "Real GDP YoY < 1.5%",
            "market_response": "Growth scare, potential recession concerns",
            "effect": "negative",
            "effect_text": "Risk-off, tech beta punished initially",
            "rationale": "PMs rotate out of high-beta/growth sectors during downturn fears",
            "confidence": "Medium-High",
            "condition": lambda data: data['yoy_growth'].iloc[-1] < 1.5 and data['yoy_growth'].iloc[-1] >= 0,
        },
        {
            "trigger": "Real GDP < 0% (contracting)",
            "market_response": "Recession pricing begins",
            "effect": "negative",
            "effect_text": "Underperforms at onset, may bottom before cycle",
            "rationale": "Tech sells off early but often leads recovery on easing expectations",
            "confidence": "High",
            "condition": lambda data: data['yoy_growth'].iloc[-1] < 0,
        },
    ],
    "fed_funds": [
        {
            "trigger": "Hike surprise (> expected)",
            "market_response": "Bond yields jump, equities sell off",
            "effect": "negative",
            "effect_text": "Tech derided, rotation to value",
            "rationale": "Higher cost of capital compresses long-duration valuations",
            "confidence": "High",
            "condition": lambda data: len(data) >= 2 and data['value'].iloc[-1] > data['value'].iloc[-2] and (data['value'].iloc[-1] - data['value'].iloc[-2]) >= 0.25,
        },
        {
            "trigger": "Cut surprise (< expected)",
            "market_response": "Risk assets rally, growth bid returns",
            "effect": "positive",
            "effect_text": "Tech outperforms, especially high-growth names",
            "rationale": "Dovish surprise improves liquidity & forward DCF assumptions",
            "confidence": "High",
            "condition": lambda data: len(data) >= 2 and data['value'].iloc[-1] < data['value'].iloc[-2] and (data['value'].iloc[-2] - data['value'].iloc[-1]) >= 0.25,
        },
        {
            "trigger": "> 5.25% Terminal Rate",
            "market_response": "Market cautious, rates seen as \"restrictive\"",
            "effect": "negative",
            "effect_text": "Persistent headwind for growth",
            "rationale": "High-rate regime = tightening financial conditions for longer",
            "confidence": "Medium-High",
            "condition": lambda data: data['value'].iloc[-1] > 5.25,
        },
        {
            "trigger": "4.0% – 5.25% Range",
            "market_response": "\"High but expected\" zone",
            "effect": "neutral",
            "effect_text": "Mixed tech sentiment",
            "rationale": "Tech can work selectively if earnings momentum is strong",
            "confidence": "High",
            "condition": lambda data: 4.0 <= data['value'].iloc[-1] <= 5.25,
        },
        {
            "trigger": "< 4.0%",
            "market_response": "Policy viewed as more neutral/accommodative",
            "effect": "positive",
            "effect_text": "Valuation tailwind, especially mid/large-cap tech",
            "rationale": "Lower rates = multiple expansion and return of speculative appetite",
            "confidence": "High",
            "condition": lambda data: data['value'].iloc[-1] < 4.0 and data['value'].iloc[-1] >= 2.5,
        },
        {
            "trigger": "< 2.5%",
            "market_response": "Emergency/zero-rate stimulus mode",
            "effect": "positive",
            "effect_text": "Speculative growth and long-duration tech favored",
            "rationale": "Historically fuels IPOs, VC rounds, unprofitable tech rallies",
            "confidence": "High",
            "condition": lambda data: data['value'].iloc[-1] < 2.5,
        },
    ],
    "treasury_yield": [
        {
            "trigger": "> 4.25%",
            "market_response": "Sharp valuation compression, growth-to-value rotation",
            "effect": "negative",
            "effect_text": "Pressure on long-duration tech (e.g. high-growth SaaS)",
            "rationale": "Discount rate increases → future earnings worth less",
            "confidence": "High",
            "condition": lambda data: data['value'].iloc[-1] > 4.25,
        },
        {
            "trigger": "3.75% – 4.25%",
            "market_response": "Cautious optimism, valuation cap on growth",
            "effect": "neutral",
            "effect_text": "Mixed to slightly negative for tech",
            "rationale": "Still elevated, but expectations are likely priced in",
            "confidence": "High",
            "condition": lambda data: 3.75 <= data['value'].iloc[-1] <= 4.25,
        },
        {
            "trigger": "3.0% – 3.75%",
            "market_response": "\"Neutral zone\"",
            "effect": "positive",
            "effect_text": "Valuation stabilizer for tech",
            "rationale": "Range historically tolerable for risk-on positioning",
            "confidence": "Medium-High",
            "condition": lambda data: 3.0 <= data['value'].iloc[-1] <= 3.75,
        },
        {
            "trigger": "< 3.0%",
            "market_response": "Risk-on environment, easing narrative grows",
            "effect": "positive",
            "effect_text": "Multiple expansion begins for growth sectors",
            "rationale": "Lower yields = more accommodative = stronger DCF values",
            "confidence": "High",
            "condition": lambda data: data['value'].iloc[-1] < 3.0,
        },
        {
            "trigger": "Rapid move > +50bps/month",
            "market_response": "Yield shock, market-wide repricing",
            "effect": "negative",
            "effect_text": "Short-term tech selloff",
            "rationale": "Institutions rotate to safety as DCFs reset, even if earnings are strong",
            "confidence": "High",
            "condition": lambda data: len(data) >= 30 and (data['value'].iloc[-1] - data['value'].iloc[-30]) > 0.5,
        },
        {
            "trigger": "Decline > 50bps in month",
            "market_response": "Rate relief, flight to quality, dovish shift",
            "effect": "positive",
            "effect_text": "Tech outperformance (especially mega-cap)",
            "rationale": "Lower yields often interpreted as easing cycle approaching",
            "confidence": "Medium-High",
            "condition": lambda data: len(data) >= 30 and (data['value'].iloc[-30] - data['value'].iloc[-1]) > 0.5,
        },
    ],
    "inflation": [
        {
            "trigger": "CPI YoY > 4.0%",
            "market_response": "Rate hike expectations rise, bonds sell off",
            "effect": "negative",
            "effect_text": "Tech valuation compression, rotation to value",
            "rationale": "High inflation = higher expected rates → discounted cash flows worth less",
            "confidence": "High",
            "condition": lambda data: data['inflation'].iloc[-1] > 4.0,
        },
        {
            "trigger": "CPI YoY 3.0% – 4.0%",
            "market_response": "Sticky inflation narrative returns",
            "effect": "neutral",
            "effect_text": "Mixed: market wary of prolonged Fed tightening",
            "rationale": "Inflation not hot enough to panic, but enough to suppress dovish pivot hopes",
            "confidence": "Medium-High",
            "condition": lambda data: 3.0 <= data['inflation'].iloc[-1] <= 4.0,
        },
        {
            "trigger": "CPI YoY 2.0% – 3.0%",
            "market_response": "Market stabilizes, inflation seen as manageable",
            "effect": "positive",
            "effect_text": "Growth sectors stabilize, long-duration tech firms benefit",
            "rationale": "Fits Fed's long-run average target range",
            "confidence": "High",
            "condition": lambda data: 2.0 <= data['inflation'].iloc[-1] < 3.0,
        },
        {
            "trigger": "CPI YoY < 2.0%",
            "market_response": "Disinflation expectations grow, yields fall",
            "effect": "positive",
            "effect_text": "Tech rallies, especially unprofitable growth",
            "rationale": "Easier Fed policy priced in; cost pressure and DCF headwinds ease",
            "confidence": "High",
            "condition": lambda data: data['inflation'].iloc[-1] < 2.0,
        },
        {
            "trigger": "CPI Surprise > 0.4% MoM",
            "market_response": "Yield spike, short-term sell-off",
            "effect": "negative",
            "effect_text": "Tech derisking in near-term",
            "rationale": "Hot prints drive algorithmic/fund rotation out of growth",
            "confidence": "High",
            "condition": lambda data: len(data) >= 2 and (data['value'].iloc[-1] / data['value'].iloc[-2] - 1) > 0.004,
        },
        {
            "trigger": "CPI Surprise < 0.2% MoM",
            "market_response": "Bond rally, dovish Fed bets rise",
            "effect": "positive",
            "effect_text": "Tech outperforms",
            "rationale": "Encourages multiple expansion and flows into risk assets",
            "confidence": "High",
            "condition": lambda data: len(data) >= 2 and (data['value'].iloc[-1] / data['value'].iloc[-2] - 1) < 0.002,
        },
    ],
    "vix": [
        {
            "trigger": "VIX > 30",
            "market_response": "Panic territory, systemic fear",
            "effect": "negative", 
            "effect_text": "Flight from high-beta tech and speculative names",
            "rationale": "Elevated risk aversion leads to deleveraging, selling long-duration assets",
            "confidence": "High",
            "condition": lambda data: data['value'].iloc[-1] > 30,
        },
        {
            "trigger": "VIX 25-30",
            "market_response": "Volatility spike, active de-risking",
            "effect": "negative",
            "effect_text": "Rotation to defensives",
            "rationale": "Signals macro concern, earnings fear, or geopolitical risk",
            "confidence": "High",
            "condition": lambda data: 25 <= data['value'].iloc[-1] <= 30,
        },
        {
            "trigger": "VIX 20-25",
            "market_response": "Watch zone, elevated caution",
            "effect": "neutral",
            "effect_text": "Mixed-to-negative for tech",
            "rationale": "Tech may lag unless supported by strong fundamentals",
            "confidence": "Medium-High",
            "condition": lambda data: 20 <= data['value'].iloc[-1] < 25,
        },
        {
            "trigger": "VIX 15-20",
            "market_response": "Neutral/steady risk conditions",
            "effect": "neutral",
            "effect_text": "Neutral; market driven more by fundamentals",
            "rationale": "Flows driven more by earnings, growth expectations",
            "confidence": "High",
            "condition": lambda data: 15 <= data['value'].iloc[-1] < 20,
        },
        {
            "trigger": "VIX < 15",
            "market_response": "Complacency regime",
            "effect": "positive",
            "effect_text": "Bullish for tech multiples and growth trades",
            "rationale": "Low volatility encourages re-risking and valuation expansion",
            "confidence": "High",
            "condition": lambda data: data['value'].iloc[-1] < 15,
        },
        {
            "trigger": "VIX spike > +5 pts in 5 days",
            "market_response": "Sudden fear event (macro or geopolitical)",
            "effect": "negative",
            "effect_text": "Tech typically underperforms short term",
            "rationale": "High-beta sectors hit first in volatility spikes",
            "confidence": "High",
            "condition": lambda data: (data['value'].iloc[-1] - data['value'].iloc[-5]) > 5 if len(data) >= 5 else False,
        },
        {
            "trigger": "VIX downtrend > 2 weeks",
            "market_response": "Sentiment improving, risk-on returning",
            "effect": "positive",
            "effect_text": "Growth and unprofitable tech begin to rally",
            "rationale": "Multiple expansion supported as investors shift out of defensives",
            "confidence": "High",
            "condition": lambda data: len(data) >= 10 and all(data['value'].iloc[i] >= data['value'].iloc[i+1] for i in range(-10, -1)),
        },
        {
            "trigger": "VIX curve inverts (front > back)",
            "market_response": "Elevated short-term risk pricing",
            "effect": "negative",
            "effect_text": "Short-term derisking underway",
            "rationale": "Often precedes deeper market stress or event risk",
            "confidence": "High",
            "condition": lambda data: False,  # Would require term structure data not available in this dataset
        },
    ],
    "pce": [
        {
            "trigger": "Real PCE YoY > 4.0%",
            "market_response": "Strong consumer demand, growth optimism",
            "effect": "positive",
            "effect_text": "Tailwind for B2C tech (eComm, AdTech, SMB SaaS)",
            "rationale": "High digital activity → higher rev growth",
            "confidence": "Medium",
            "condition": lambda data: data['yoy_growth'].iloc[-1] > 4.0,
        },
        {
            "trigger": "Real PCE YoY 2.0%–4.0%",
            "market_response": "Steady economic activity",
            "effect": "positive",
            "effect_text": "Supportive for broad tech",
            "rationale": "Signals stable demand with manageable inflation pressures",
            "confidence": "High",
            "condition": lambda data: 2.0 <= data['yoy_growth'].iloc[-1] <= 4.0,
        },
        {
            "trigger": "Real PCE YoY < 2.0%",
            "market_response": "Demand slowdown concern",
            "effect": "negative",
            "effect_text": "Drag on B2C software, digital services",
            "rationale": "Weak consumption = earnings risk for eComm/AdTech",
            "confidence": "Medium-High",
            "condition": lambda data: data['yoy_growth'].iloc[-1] < 2.0 and data['yoy_growth'].iloc[-1] >= 0,
        },
        {
            "trigger": "Real PCE < 0%",
            "market_response": "Recessionary conditions",
            "effect": "negative",
            "effect_text": "Defensive posturing, tech derisking",
            "rationale": "Signals demand contraction and potential layoffs",
            "confidence": "High",
            "condition": lambda data: data['yoy_growth'].iloc[-1] < 0,
        },
    ],
    "pcepi": [
        {
            "trigger": "PCEPI YoY > 3.5%",
            "market_response": "Hawkish Fed expectations, rate fears",
            "effect": "negative",
            "effect_text": "Tech valuation compression",
            "rationale": "Rate hikes repriced into market → hurts long-duration tech",
            "confidence": "High",
            "condition": lambda data: data['yoy_growth'].iloc[-1] > 3.5,
        },
        {
            "trigger": "PCEPI YoY 2.5%–3.5%",
            "market_response": "Inflation sticky, but manageable",
            "effect": "neutral",
            "effect_text": "Neutral to Cautious",
            "rationale": "Could delay Fed pivot or suggest prolonged margin pressures",
            "confidence": "Medium-High",
            "condition": lambda data: 2.5 <= data['yoy_growth'].iloc[-1] <= 3.5,
        },
        {
            "trigger": "PCEPI YoY < 2.5%",
            "market_response": "Disinflation narrative gains ground",
            "effect": "positive",
            "effect_text": "Tech-friendly rate environment",
            "rationale": "Eases pressure on multiples and supports rotation into growth",
            "confidence": "High",
            "condition": lambda data: data['yoy_growth'].iloc[-1] < 2.5 and data['yoy_growth'].iloc[-1] >= 2.0,
        },
        {
            "trigger": "PCEPI YoY < 2.0%",
            "market_response": "Deflation fears possible",
            "effect": "neutral",
            "effect_text": "Mixed (depends on growth data)",
            "rationale": "Could raise demand concerns even as valuations improve",
            "confidence": "Medium",
            "condition": lambda data: data['yoy_growth'].iloc[-1] < 2.0,
        },
    ],
    "nasdaq": [
        {
            "trigger": "10-day drop > -5%",
            "market_response": "Broad de-risking, rotation to defensives",
            "effect": "negative",
            "effect_text": "Short-term tech pullback",
            "rationale": "Often signals macro worry or earnings disappointment across growth sectors",
            "confidence": "High",
            "condition": lambda data: len(data) >= 10 and (data['value'].iloc[-1] / data['value'].iloc[-10] - 1) < -0.05,
        },
        {
            "trigger": "10-day gain > +5%",
            "market_response": "Risk-on rally, macro tailwind priced in",
            "effect": "positive",
            "effect_text": "Tech sentiment rebounds",
            "rationale": "Suggests favorable positioning or macro relief (e.g., falling yields, Fed pivot)",
            "confidence": "High",
            "condition": lambda data: len(data) >= 10 and (data['value'].iloc[-1] / data['value'].iloc[-10] - 1) > 0.05,
        },
        {
            "trigger": "Correction from recent high > -10%",
            "market_response": "Technically oversold, caution increases",
            "effect": "negative",
            "effect_text": "Raises concerns of broader shift in positioning",
            "rationale": "Technical signals trigger systematic de-risking",
            "confidence": "Medium-High",
            "condition": lambda data: len(data) >= 60 and (data['value'].iloc[-1] / data['value'].iloc[-60:].max() - 1) < -0.1,
        },
        {
            "trigger": "New 30-day high",
            "market_response": "Momentum accelerates",
            "effect": "positive",
            "effect_text": "Positive sentiment and flows into tech",
            "rationale": "Bullish breakout brings flows from momentum and quant-driven funds",
            "confidence": "High",
            "condition": lambda data: len(data) >= 30 and data['value'].iloc[-1] > data['value'].iloc[-30:-1].max(),
        },
        {
            "trigger": "10-Year T↑ > 4.25%",
            "market_response": "NASDAQ stalls or declines",
            "effect": "negative",
            "effect_text": "Tech derated, especially high-multiple names",
            "rationale": "Rate pressure lowers fair value estimates",
            "confidence": "High",
            "condition": lambda data: False,  # Would require treasury yield data not directly in NASDAQ dataset
        },
        {
            "trigger": "CPI or PCEPI surprise > 0.4% MoM",
            "market_response": "Index pulls back sharply",
            "effect": "negative",
            "effect_text": "Valuation compression begins",
            "rationale": "Signals sticky inflation = no Fed relief soon",
            "confidence": "High",
            "condition": lambda data: False,  # Would require CPI/PCEPI data not directly in NASDAQ dataset
        },
        {
            "trigger": "Fed dovish surprise (cut or dot plot shift down)",
            "market_response": "NASDAQ jumps on liquidity re-pricing",
            "effect": "positive",
            "effect_text": "Growth outperforms",
            "rationale": "Rate-sensitive names benefit from multiple expansion",
            "confidence": "High",
            "condition": lambda data: False,  # Would require Fed decision data not in dataset
        },
        {
            "trigger": "VIX > 25",
            "market_response": "Vol spike leads to NASDAQ drop",
            "effect": "negative",
            "effect_text": "Tech underperforms in risk-off rebalancing",
            "rationale": "Tech = high beta → volatility-induced deleveraging",
            "confidence": "Medium-High",
            "condition": lambda data: False,  # Would require VIX data not directly in NASDAQ dataset
        },
    ],
    "software_ppi": [
        {
            "trigger": "PPI YoY > +4.0%",
            "market_response": "Signals strong pricing power",
            "effect": "positive",
            "effect_text": "Bullish for software margin outlook",
            "rationale": "Suggests companies can raise prices without losing customers",
            "confidence": "Medium-High",
            "condition": lambda data: data['yoy_growth'].iloc[-1] > 4.0,
        },
        {
            "trigger": "PPI YoY 2.0% – 4.0%",
            "market_response": "Normalized pricing trends",
            "effect": "neutral",
            "effect_text": "Neutral to supportive",
            "rationale": "Implies pricing is keeping pace with cost inflation",
            "confidence": "Medium",
            "condition": lambda data: 2.0 <= data['yoy_growth'].iloc[-1] <= 4.0,
        },
        {
            "trigger": "PPI YoY < 2.0%",
            "market_response": "Weak pricing power, deflationary signal",
            "effect": "negative",
            "effect_text": "Margin pressure for SaaS, especially SMB-focused",
            "rationale": "Suggests increased competition or customer pushback on pricing",
            "confidence": "Medium",
            "condition": lambda data: 0 <= data['yoy_growth'].iloc[-1] < 2.0,
        },
        {
            "trigger": "PPI YoY < 0% (Deflation)",
            "market_response": "Pricing power breakdown",
            "effect": "negative",
            "effect_text": "May indicate churn risk or commoditization",
            "rationale": "Often signals oversupply, macro weakness, or tightening IT budgets",
            "confidence": "Medium-High",
            "condition": lambda data: data['yoy_growth'].iloc[-1] < 0,
        },
        {
            "trigger": "Rising YoY trend > 3 straight quarters",
            "market_response": "Pricing power expanding",
            "effect": "positive",
            "effect_text": "Supports valuation stability or expansion",
            "rationale": "Indicates strong demand and pricing leverage",
            "confidence": "Medium-High",
            "condition": lambda data: len(data) >= 9 and all(data['yoy_growth'].iloc[-i] > data['yoy_growth'].iloc[-i-3] for i in range(1, 4)),
        },
        {
            "trigger": "Falling trend > 2 quarters",
            "market_response": "Competitive pressures or macro softness",
            "effect": "negative",
            "effect_text": "Raises concern over growth and margin sustainability",
            "rationale": "May indicate market saturation or budget constraints",
            "confidence": "Medium",
            "condition": lambda data: len(data) >= 6 and all(data['yoy_growth'].iloc[-i] < data['yoy_growth'].iloc[-i-3] for i in range(1, 3)),
        },
    ],
    "data_ppi": [
        {
            "trigger": "PPI YoY > +3.5%",
            "market_response": "Strong demand & pricing power",
            "effect": "positive",
            "effect_text": "Margin and growth tailwind for cloud/IaaS",
            "rationale": "Suggests enterprise IT spending is strong; providers can raise prices",
            "confidence": "Medium-High",
            "condition": lambda data: data['yoy_growth'].iloc[-1] > 3.5,
        },
        {
            "trigger": "PPI YoY 2.0% – 3.5%",
            "market_response": "Stable to moderate pricing power",
            "effect": "neutral",
            "effect_text": "Neutral to positive",
            "rationale": "Reflects balanced environment of demand and competition",
            "confidence": "Medium",
            "condition": lambda data: 2.0 <= data['yoy_growth'].iloc[-1] <= 3.5,
        },
        {
            "trigger": "PPI YoY < 2.0%",
            "market_response": "Weakening demand or heightened competition",
            "effect": "negative",
            "effect_text": "Margin risk for cloud providers",
            "rationale": "Indicates potential pricing pressure, possibly from macro tightening or commoditization",
            "confidence": "Medium",
            "condition": lambda data: 0 <= data['yoy_growth'].iloc[-1] < 2.0,
        },
        {
            "trigger": "PPI YoY < 0%",
            "market_response": "Deflationary pricing, service commoditization",
            "effect": "negative",
            "effect_text": "Structural margin concern",
            "rationale": "May reflect price wars or lack of differentiation among providers",
            "confidence": "Medium-High",
            "condition": lambda data: data['yoy_growth'].iloc[-1] < 0,
        },
        {
            "trigger": "Rising PPI trend 3+ quarters",
            "market_response": "Strength in cloud/data infrastructure pricing",
            "effect": "positive",
            "effect_text": "Supports bullish case for IaaS/enterprise",
            "rationale": "Indicates sustained demand and pricing discipline",
            "confidence": "Medium-High",
            "condition": lambda data: len(data) >= 9 and all(data['yoy_growth'].iloc[-i] > data['yoy_growth'].iloc[-i-3] for i in range(1, 4)),
        },
        {
            "trigger": "Falling PPI trend 2+ quarters",
            "market_response": "Risk of oversupply or procurement cuts",
            "effect": "negative",
            "effect_text": "Headwind for margin and revenue forecasts",
            "rationale": "May indicate slowing enterprise spend or competitive pressure",
            "confidence": "Medium",
            "condition": lambda data: len(data) >= 6 and all(data['yoy_growth'].iloc[-i] < data['yoy_growth'].iloc[-i-3] for i in range(1, 3)),
        },
    ],
    "unemployment": [
        {
            "trigger": "< 3.5%",
            "market_response": "Overheating risk, wage pressure builds",
            "effect": "negative",
            "effect_text": "Margin pressure for labor-intensive SaaS",
            "rationale": "Signals tight labor market → wage inflation → cost headwinds",
            "confidence": "Medium-High",
            "condition": lambda data: data['value'].iloc[-1] < 3.5,
        },
        {
            "trigger": "3.5% – 4.0%",
            "market_response": "Strong labor market, solid demand",
            "effect": "positive",
            "effect_text": "Neutral to positive (esp. SMB SaaS, Consumer Internet)",
            "rationale": "Demand supports topline growth; margin pressure depends on wage trends",
            "confidence": "High",
            "condition": lambda data: 3.5 <= data['value'].iloc[-1] <= 4.0,
        },
        {
            "trigger": "4.0% – 4.5%",
            "market_response": "Balanced economy",
            "effect": "positive",
            "effect_text": "Constructive for tech + potential Fed dovishness",
            "rationale": "Room for wage relief + demand stability",
            "confidence": "Medium-High",
            "condition": lambda data: 4.0 <= data['value'].iloc[-1] <= 4.5,
        },
        {
            "trigger": "> 4.5%",
            "market_response": "Growth scare begins, Fed pivot expectations",
            "effect": "neutral",
            "effect_text": "Mixed; tech may benefit from lower rate outlook",
            "rationale": "Rising unemployment may soften demand but boost rate-sensitive tech multiples",
            "confidence": "Medium",
            "condition": lambda data: data['value'].iloc[-1] > 4.5 and data['value'].iloc[-1] <= 5.5,
        },
        {
            "trigger": "> 5.5%",
            "market_response": "Recession fears front and center",
            "effect": "negative",
            "effect_text": "Tech risk-off; earnings and hiring concerns",
            "rationale": "Cyclical tech (ads, eComm) suffers; software hiring slows",
            "confidence": "High",
            "condition": lambda data: data['value'].iloc[-1] > 5.5,
        },
        {
            "trigger": "Surprise rise > +0.3% in 1 month",
            "market_response": "Flash recession signal",
            "effect": "negative",
            "effect_text": "De-risking in equities",
            "rationale": "Abrupt labor weakness shakes confidence in soft landing",
            "confidence": "High",
            "condition": lambda data: len(data) >= 2 and data['value'].iloc[-1] - data['value'].iloc[-2] > 0.3,
        },
        {
            "trigger": "3-month uptrend",
            "market_response": "Fed pivot odds rise",
            "effect": "positive",
            "effect_text": "Tech may benefit from easing rate expectations",
            "rationale": "Historically precedes rate cut cycles and rallies in long-duration assets",
            "confidence": "Medium",
            "condition": lambda data: len(data) >= 3 and data['value'].iloc[-1] > data['value'].iloc[-2] > data['value'].iloc[-3],
        },
        {
            "trigger": "3-month downtrend",
            "market_response": "Fed tightening bias sustained",
            "effect": "negative",
            "effect_text": "Wage inflation concerns return",
            "rationale": "May prolong higher for longer interest rate regime",
            "confidence": "Medium",
            "condition": lambda data: len(data) >= 3 and data['value'].iloc[-1] < data['value'].iloc[-2] < data['value'].iloc[-3],
        },
    ],
    "consumer_sentiment": [
        {
            "trigger": "Consumer Sentiment > 105",
            "market_response": "Bullish consumer outlook, strong spending environment",
            "effect": "positive",
            "effect_text": "Consumer tech and services thrive",
            "rationale": "High consumer confidence correlates with higher discretionary spending",
            "confidence": "High",
            "condition": lambda data: data['value'].iloc[-1] > 105,
        },
        {
            "trigger": "Consumer Sentiment 95-105",
            "market_response": "Neutral to positive consumer outlook",
            "effect": "positive",
            "effect_text": "Stable environment for consumer-facing tech",
            "rationale": "Average sentiment suggests normal spending patterns",
            "confidence": "Medium",
            "condition": lambda data: 95 <= data['value'].iloc[-1] <= 105,
        },
        {
            "trigger": "Consumer Sentiment 85-95",
            "market_response": "Cautious consumer outlook",
            "effect": "neutral",
            "effect_text": "Mixed impact on consumer tech",
            "rationale": "Below-average sentiment may lead to selective spending",
            "confidence": "Medium",
            "condition": lambda data: 85 <= data['value'].iloc[-1] < 95,
        },
        {
            "trigger": "Consumer Sentiment < 85",
            "market_response": "Bearish consumer outlook, potential spending pullback",
            "effect": "negative",
            "effect_text": "Headwind for consumer-facing tech",
            "rationale": "Low consumer confidence often precedes reduced discretionary spending",
            "confidence": "High",
            "condition": lambda data: data['value'].iloc[-1] < 85,
        },
        {
            "trigger": "Rising trend (3+ consecutive months)",
            "market_response": "Improving consumer outlook",
            "effect": "positive",
            "effect_text": "Tailwind for consumer-facing tech",
            "rationale": "Trend direction often more important than absolute level",
            "confidence": "Medium-High",
            "condition": lambda data: len(data) >= 3 and data['value'].iloc[-1] > data['value'].iloc[-2] and data['value'].iloc[-2] > data['value'].iloc[-3],
        },
        {
            "trigger": "Falling trend (3+ consecutive months)",
            "market_response": "Deteriorating consumer outlook",
            "effect": "negative",
            "effect_text": "Caution for consumer-facing tech",
            "rationale": "Persistent downtrends often signal broader economic concerns",
            "confidence": "Medium-High",
            "condition": lambda data: len(data) >= 3 and data['value'].iloc[-1] < data['value'].iloc[-2] and data['value'].iloc[-2] < data['value'].iloc[-3],
        },
    ],
    "job_postings": [
        {
            "trigger": "> +20% YoY",
            "market_response": "Hiring boom, expansionary signals",
            "effect": "positive",
            "effect_text": "Bullish for SMB SaaS, DevOps, Cloud Infra",
            "rationale": "Suggests confident tech orgs are scaling rapidly, often tied to topline growth",
            "confidence": "Medium-High",
            "condition": lambda data: data['yoy_growth'].iloc[-1] > 20,
        },
        {
            "trigger": "+5% to +20% YoY",
            "market_response": "Healthy labor market recovery",
            "effect": "positive",
            "effect_text": "Constructive for tech sector recovery",
            "rationale": "Indicates stabilization or acceleration in post-layoff cycle",
            "confidence": "High",
            "condition": lambda data: 5 <= data['yoy_growth'].iloc[-1] <= 20,
        },
        {
            "trigger": "-5% to +5% YoY",
            "market_response": "Flat or stagnating demand",
            "effect": "neutral",
            "effect_text": "Cautious read on growth acceleration",
            "rationale": "Hiring plateau may suggest optimization phase or macro uncertainty",
            "confidence": "Medium",
            "condition": lambda data: -5 <= data['yoy_growth'].iloc[-1] < 5,
        },
        {
            "trigger": "-20% to -5% YoY",
            "market_response": "Broad hiring slowdown",
            "effect": "negative",
            "effect_text": "Growth moderation / margin prioritization",
            "rationale": "Reflects tech belt-tightening, especially in SMBs or VC-backed startups",
            "confidence": "High",
            "condition": lambda data: -20 <= data['yoy_growth'].iloc[-1] < -5,
        },
        {
            "trigger": "< -20% YoY",
            "market_response": "Hiring recession, cost-cutting cycle",
            "effect": "negative",
            "effect_text": "High risk for earnings pressure or headcount cuts",
            "rationale": "Typically aligns with layoffs, funding pullbacks, demand softening",
            "confidence": "High",
            "condition": lambda data: data['yoy_growth'].iloc[-1] < -20,
        },
        {
            "trigger": "3-month acceleration in YoY growth",
            "market_response": "Reinvestment cycle may be starting",
            "effect": "positive",
            "effect_text": "Bullish shift in sentiment",
            "rationale": "Historically precedes increased tech hiring",
            "confidence": "Medium",
            "condition": lambda data: len(data) >= 3 and data['yoy_growth'].iloc[-1] > data['yoy_growth'].iloc[-2] > data['yoy_growth'].iloc[-3],
        },
        {
            "trigger": "3-month deceleration in YoY growth",
            "market_response": "Slowing confidence or early demand warning",
            "effect": "negative",
            "effect_text": "Suggests looming revisions or slower guidance",
            "rationale": "Often precedes more conservative outlook",
            "confidence": "Medium-High",
            "condition": lambda data: len(data) >= 3 and data['yoy_growth'].iloc[-1] < data['yoy_growth'].iloc[-2] < data['yoy_growth'].iloc[-3],
        },
        {
            "trigger": "YoY trough then +5% rebound (V-shape)",
            "market_response": "Recovery signal",
            "effect": "positive",
            "effect_text": "Re-entry point for tech exposure",
            "rationale": "Indicates broader recovery in tech hiring",
            "confidence": "Medium-High",
            "condition": lambda data: len(data) >= 3 and data['yoy_growth'].iloc[-3] > data['yoy_growth'].iloc[-2] and data['yoy_growth'].iloc[-1] > data['yoy_growth'].iloc[-2] and data['yoy_growth'].iloc[-1] - data['yoy_growth'].iloc[-2] >= 5,
        },
    ]
}